# GitGuardian Configuration
# This file tells GitGuardian to ignore certain patterns

paths-ignore:
  - 'script.js'  # Contains intentionally public Supabase anon key
  - 'admin/admin.js'  # May contain public keys

# These are public keys that are safe to expose
# - Supabase anon keys are designed to be public
# - Stripe publishable keys are designed to be public